### ISSUE TITLE
Provide via conda-forge?

### ISSUE THREAD

**Issue by jgliss** [bartromgens/geojsoncontour#21]
Hi, 

many thanks for developing this package. Are you planning to also release is via conda package manager (e.g. conda-forge channel)? It is very easy to setup, based on your PyPi release. 

Cheers, 
Jonas

**Comment by bartromgens** [comment]
@jgliss I have no experience with publishing conda packages and did not plan to support it, but if there is a clear demand and easy to setup, I don't mind adding it.

**Comment by jgliss** [comment]
@bartromgens thanks, I understand. We will likely use it in [pyaerocom](https://github.com/metno/pyaerocom) which is an open source software for climate model data analysis which feeds several web interfaces, such as the [AeroCom Evaluation interface](https://aerocom-evaluation.met.no/main.php?project=aerocom), which is based on precomputed json files. 

In an upcoming release we plan to also display countourmaps of the model output, for which we intend to use geojsoncontour and it would make life a little easier if it was available via conda, but pip also works. I was just curious :)

**Comment by jgriesfeller** [comment]
Since pyaerocom stopped distribution via conda, this issue is not valid anymore. Closing it therefore.

**Comment by pedroaugustosmribeiro** [comment]
Hello,

I also have interest on a conda version of this package, which could then be submitted to conda-forge.
Here's a recipe (meta.yaml)

```yaml
{% set name = "geojsoncontour" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/geojsoncontour-{{ version }}.tar.gz
  sha256: a344ec28baa1efd695b10da2972e91e5528265500dc9b29e2d1adab9cf1ea349

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - geojson
    - numpy
    - matplotlib-base
    - xarray

test:
  imports:
    - geojsoncontour
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/bartromgens/geojsoncontour
  summary: Convert matplotlib contour plots to geojson
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - bartromgens
    - jgriesfeller
```
